### ISSUE TITLE
Selector (class) restrictions

### ISSUE THREAD

**Issue by slcr** [nico-martin/AdvancedWPLink#1]
the selector-field has some character-restrictions. I'd like to add a class-array to it like this:

![bildschirmfoto 2016-11-19 um 08 07 56](https://cloud.githubusercontent.com/assets/71357/20453771/7cb53564-ae2f-11e6-90a7-715dc936d465.png)

to prevent having to duplicate my existing classes.

**edit** first ticket! 🎉

**Comment by nico-martin** [comment]
There's no need to add the `.`. Just two classes separated by a space would work `btn red`

**Comment by nico-martin** [comment]
There's no need to add the `.`. Just two classes separated by a space would work `btn red`
